import fs from 'fs';
import path from 'path';
import { EmailData } from '../types';

export const exact50DemoEmails: EmailData[] = [
  // 1. UNIVERSITY CLOSURE (CRITICAL)
  {
    id: "email-srm-001",
    sender: "registrar.office@srmap.edu.in",
    senderName: "Registrar Office, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    cc: ["dean.seas@srmap.edu.in", "students.seas@srmap.edu.in"],
    subject: "CIRCULAR: University Closure on Sept 25 and Compensatory Working Day",
    body: `Dear Faculty, Staff, and Students of SRM University-AP,\n\nIn view of severe continuous rainfall and poor road conditions leading to the Neerukonda campus, the University remained closed on Friday, September 25, 2026. All academic lectures, laboratory sessions, and evaluations scheduled for that day stand rescheduled.\n\nCOMPENSATORY WORKING DAY NOTIFICATION:\nSaturday, October 10, 2026, will be observed as a compensatory working day. Friday's timetable will be strictly followed.\n\nStudents residing in campus hostels are requested to remain indoors during severe wind advisories.\n\nBy Order,\nDr. Prem Kumar\nRegistrar, SRM University-AP, Andhra Pradesh`,
    timestamp: "2026-09-25T07:30:00.000Z",
    dateFormatted: "Sep 25, 2026 · 7:30 AM",
    category: "ADMINISTRATION",
    priority: "CRITICAL",
    priorityScore: 98,
    priorityReason: "Emergency university closure circular and mandatory compensatory academic schedule on Oct 10.",
    categoryReason: "Official administrative circular detailing university operational closure and revised working days.",
    summary: "University closed Sept 25 due to heavy rainfall. Saturday Oct 10 declared compensatory working day following Friday timetable.",
    actionRequired: true,
    actionText: "Note compensatory working day on Saturday, October 10 (Friday timetable applies)",
    actionDeadline: "Oct 10, 2026",
    deadlineDate: "2026-10-10T08:30:00.000Z",
    location: "SRM University-AP, Neerukonda Campus",
    affectedGroup: "All SRM AP Students, Faculty & Staff",
    urgency: "CRITICAL",
    tags: ["circular", "closure", "compensatory-day", "registrar", "weather"],
    isRead: false,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-closure-schedule",
    relatedCalendarEventId: "cal-srm-005",
    isCalendarAdded: true
  },

  // 2. ROBOTICS WORKSHOP (TECHFEST IIT BOMBAY) (HIGH)
  {
    id: "email-srm-002",
    sender: "communications@srmap.edu.in",
    senderName: "Directorate of Communications, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    cc: ["dean.seas@srmap.edu.in"],
    subject: "Hands-On Workshop on Robotics in Collaboration with Techfest (IIT Bombay)",
    body: `Dear Students of School of Engineering and Sciences (SEAS),\n\nSRM University-AP, in collaboration with Techfest (IIT Bombay), is organising an intensive, hands-on Workshop on Robotics for engineering scholars.\n\nEvent Details:\n- Date: Wednesday, September 30, 2026\n- Time: 10:00 AM – 4:00 PM\n- Venue: Room S202, SR Block, SRM University-AP\n- Key Topics: Autonomous Kinematics, ROS Integration, Sensor Fusion, Microcontroller Interfacing\n\nContact Person:\nDr Teja Krishna Mamidi\nAssistant Professor, Department of Mechanical Engineering\nSchool of Engineering and Sciences, SRM University-AP\n\nParticipants must carry a laptop with Ubuntu 22.04 LTS or ROS installed. Limited to 80 verified seats.\n\nDirectorate of Communications\nSRM University-AP, Andhra Pradesh`,
    timestamp: "2026-09-28T09:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 9:00 AM",
    category: "EVENTS",
    priority: "HIGH",
    priorityScore: 84,
    priorityReason: "High-value robotics workshop with IIT Bombay happening tomorrow in S202 SR Block.",
    categoryReason: "Institutional engineering workshop and technical training series.",
    summary: "Hands-on robotics workshop in collaboration with Techfest IIT Bombay on Sept 30 at S202 SR Block.",
    actionRequired: true,
    actionText: "Report to Room S202 SR Block by 9:45 AM with laptop",
    actionDeadline: "Sep 30, 2026 · 9:45 AM",
    deadlineDate: "2026-09-30T04:15:00.000Z",
    eventDate: "2026-09-30T04:30:00.000Z",
    location: "S202, SR Block",
    affectedGroup: "SEAS B.Tech Students",
    urgency: "HIGH",
    tags: ["robotics", "techfest", "iit-bombay", "workshop", "mechanical", "seas"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-robotics-workshop",
    relatedCalendarEventId: "cal-srm-002"
  },

  // 3. EXAM VENUE SHIFT (CRITICAL)
  {
    id: "email-srm-003",
    sender: "hod.cse@srmap.edu.in",
    senderName: "HOD Computer Science & Engineering",
    recipient: "demo.student@srmap.edu.in",
    cc: ["dean.seas@srmap.edu.in"],
    subject: "URGENT: Tomorrow's CSE 204 Exam Shifted to S202, SR Block",
    body: `ATTENTION B.TECH CSE SEMESTER 3 STUDENTS:\n\nDue to technical lab testing in Central Lecture Hall A, tomorrow's Mid-Semester Examination for CSE 204: Design and Analysis of Algorithms has been relocated.\n\nREVISED LOGISTICS:\n- Course: CSE 204 Design & Analysis of Algorithms\n- Date: Wednesday, September 30, 2026\n- Slot: 10:00 AM – 1:00 PM\n- NEW VENUE: Room S202, SR Block (2nd Floor)\n- REPORTING CUTOFF: 9:30 AM sharp\n\nPlease carry your physical printed Hall Ticket and Student ID card. Entry closes at 9:45 AM.\n\nDr. Murali Krishna\nHead, Department of Computer Science and Engineering\nSchool of Engineering and Sciences, SRM University-AP`,
    timestamp: "2026-09-29T08:15:00.000Z",
    dateFormatted: "Sep 29, 2026 · 8:15 AM",
    category: "EXAMS",
    priority: "CRITICAL",
    priorityScore: 99,
    priorityReason: "Emergency examination venue relocation for CSE 204 Algorithms right before morning exam slot.",
    categoryReason: "Critical examination administration logistics.",
    summary: "Tomorrow's CSE 204 Algorithms exam relocated to Room S202, SR Block. Reporting time 9:30 AM sharp.",
    actionRequired: true,
    actionText: "Report to Room S202 SR Block by 9:30 AM for CSE 204 Algorithms exam",
    actionDeadline: "Tomorrow, 9:30 AM",
    deadlineDate: "2026-09-30T04:00:00.000Z",
    eventDate: "2026-09-30T04:30:00.000Z",
    location: "S202, SR Block",
    affectedGroup: "B.Tech CSE Semester 3",
    urgency: "CRITICAL",
    tags: ["exam", "venue-change", "cse204", "sr-block", "algorithms"],
    isRead: false,
    source: "demo",
    systemOrigin: "Exam System",
    threadId: "thread-cse204-exam",
    relatedCalendarEventId: "cal-srm-001"
  },

  // 4. ATTENDANCE SHORTAGE WARNING (HIGH)
  {
    id: "email-srm-004",
    sender: "dean.seas@srmap.edu.in",
    senderName: "Office of the Dean, SEAS",
    recipient: "demo.student@srmap.edu.in",
    subject: "Attendance Shortage Notice – CSE 204 & CSE 207 (Below 75%)",
    body: `Dear Muthuselvam (B.Tech CSE, Sem 3),\n\nThis is an official intimation from the SEAS Academic Cell regarding your biometric and classroom attendance record.\n\nCURRENT DEFICIT STATUS:\n- CSE 204 (Design and Analysis of Algorithms): 71.2%\n- CSE 207 (Digital Electronics): 68.4%\n\nUnder university academic bylaws, students below 75% attendance face debarment from end-semester examinations.\n\nMANDATORY ACTION:\nSubmit your signed medical condonation explanation form and physician certificates in person to Room 114, Administrative Block before Friday, October 2, 2026, 5:00 PM.\n\nAcademic Evaluation Cell\nSchool of Engineering and Sciences, SRM University-AP`,
    timestamp: "2026-09-28T14:30:00.000Z",
    dateFormatted: "Sep 28, 2026 · 2:30 PM",
    category: "ATTENDANCE",
    priority: "HIGH",
    priorityScore: 88,
    priorityReason: "Attendance warning below 75% in two core subjects; risk of semester exam debarment.",
    categoryReason: "Mandatory student attendance compliance warning and debarment prevention.",
    summary: "Attendance below 75% in CSE 204 and CSE 207. Submit condonation forms to Room 114 before Friday 5 PM.",
    actionRequired: true,
    actionText: "Submit signed attendance condonation form to Room 114 before Friday 5:00 PM",
    actionDeadline: "Friday, Oct 2, 2026 · 5:00 PM",
    deadlineDate: "2026-10-02T11:30:00.000Z",
    location: "Room 114, Administrative Block",
    affectedGroup: "Students with attendance shortage",
    urgency: "HIGH",
    tags: ["attendance", "debarment-risk", "seas", "condonation", "room-114"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-attendance-warning"
  },

  // 5. ACM RECRUITMENT 2026 (MEDIUM)
  {
    id: "email-srm-005",
    sender: "acm.core@srmap.edu.in",
    senderName: "ACM Student Chapter, SRM AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "ACM Student Chapter Recruitment 2026 — Applications Now Open!",
    body: `Dear Tech Enthusiasts,\n\nThe ACM Student Chapter at SRM University-AP announces recruitment for the academic year 2026-2027!\n\nOPEN TEAMS:\n1. Research & Development (Competitive Coding, Systems, ML)\n2. Events Team (Hackathons, Workshops, Speaker Sessions)\n3. Social Media & Content (Tech Writing, Design)\n4. PR and Sponsorship (Outreach, Partner Relations)\n5. Documentation & Logistics (Git management, reporting)\n\nEligibility: Open to all years and disciplines across SEAS.\nDeadline: September 30, 2026 at 11:59 PM.\n\nACM Student Chapter\nSRM AP, Andhra Pradesh`,
    timestamp: "2026-09-24T11:00:00.000Z",
    dateFormatted: "Sep 24, 2026 · 11:00 AM",
    category: "STUDENT CLUBS",
    priority: "MEDIUM",
    priorityScore: 65,
    priorityReason: "Annual student chapter recruitment opportunity with firm deadline on September 30.",
    categoryReason: "Official ACM Student Chapter recruitment drive and technical committee enrollment.",
    summary: "ACM Student Chapter applications open across R&D, Events, PR, and Social Media until Sept 30.",
    actionRequired: true,
    actionText: "Submit ACM recruitment application form before September 30 deadline",
    actionDeadline: "Sep 30, 2026 · 11:59 PM",
    deadlineDate: "2026-09-30T18:29:00.000Z",
    location: "Online / Student Portal",
    affectedGroup: "All SRM AP Students",
    urgency: "MEDIUM",
    tags: ["acm", "recruitment", "student-club", "coding", "rd"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-acm-recruitment"
  },

  // 6. STARTUP WARS POSTPONED (HIGH)
  {
    id: "email-srm-006",
    sender: "ecell@srmap.edu.in",
    senderName: "SRMAP - Entrepreneurship Cell",
    recipient: "demo.student@srmap.edu.in",
    subject: "IMPORTANT: STARTUP WARS 2026 Postponed",
    body: `Dear Registered Founders and Student Teams,\n\nThis is to notify all registered participants that STARTUP WARS, originally scheduled for September 21, 2026, has been postponed.\n\nDue to the ongoing auditorium acoustic refurbishment and mentor panel synchronization, the revised competition schedule will be communicated shortly.\n\nAll existing pitch deck submissions and team registrations remain valid and locked.\n\nDirectorate of Entrepreneurship & Innovation\nSRM University-AP, Andhra Pradesh`,
    timestamp: "2026-09-20T16:00:00.000Z",
    dateFormatted: "Sep 20, 2026 · 4:00 PM",
    category: "ENTREPRENEURSHIP",
    priority: "HIGH",
    priorityScore: 82,
    priorityReason: "Scheduled institutional entrepreneurship competition postponed; invalidates previous timeline.",
    categoryReason: "Directorate of Entrepreneurship event schedule update.",
    summary: "STARTUP WARS postponed from Sept 21. Revised pitching dates to be notified by E-Cell.",
    actionRequired: true,
    actionText: "Disregard previous Sept 21 schedule; monitor inbox for revised pitch date",
    actionDeadline: "TBA",
    location: "University Incubation Center",
    affectedGroup: "Registered E-Cell Startup Teams",
    urgency: "HIGH",
    tags: ["ecell", "startup-wars", "postponed", "pitching", "entrepreneurship"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-startup-wars"
  },

  // 7. CEL MENTOR REVIEW (HIGH)
  {
    id: "email-srm-007",
    sender: "cel@srmap.edu.in",
    senderName: "Center for Entrepreneurial Learning (CEL)",
    recipient: "demo.student@srmap.edu.in",
    subject: "Submission of Presentations & Mentor Review Schedule — CEL Track",
    body: `Dear Entrepreneurship Cohort,\n\nPlease take careful note of today's mandatory presentation deadlines and review venue allocations:\n\n1. Submission of Slide Decks:\nDeadline: 12:00 PM Sharp via the CEL Portal.\n\n2. Mentor Review Venue Schedule:\n- Rakesh Sir's Teams: Report to the Directorate of Entrepreneurship by 3:50 PM. Presentation session commences at 4:00 PM.\n- Thirumali Sir's Teams: Remain seated in regular classroom CV 302 and await your scheduled evaluation slot.\n\nCenter for Entrepreneurial Learning\nSRM University-AP`,
    timestamp: "2026-09-29T06:30:00.000Z",
    dateFormatted: "Sep 29, 2026 · 6:30 AM",
    category: "ENTREPRENEURSHIP",
    priority: "HIGH",
    priorityScore: 86,
    priorityReason: "Strict submission deadline at 12:00 PM followed by in-person mentor review today at 3:50 PM.",
    categoryReason: "Mandatory academic curriculum review in entrepreneurial learning.",
    summary: "CEL slide decks due by 12:00 PM. Rakesh Sir's teams report to Directorate by 3:50 PM; Thirumali Sir's teams in classroom.",
    actionRequired: true,
    actionText: "Upload pitch deck before 12:00 PM; report to Directorate by 3:50 PM for mentor review",
    actionDeadline: "Today, 12:00 PM",
    deadlineDate: "2026-09-29T06:30:00.000Z",
    location: "Directorate of Entrepreneurship / CV 302",
    affectedGroup: "CEL Semester 3 Enrolled Students",
    urgency: "HIGH",
    tags: ["cel", "mentor-review", "pitch-deck", "entrepreneurship", "deadline"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-cel-mentor"
  },

  // 8. GDG GOOGLE SOLUTION HUNT (MEDIUM)
  {
    id: "email-srm-008",
    sender: "communications@srmap.edu.in",
    senderName: "GDG on Campus — SRM University AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "Google Solution Hunt Challenge 2026 — Think, Build, Present, Win",
    body: `Greetings Developers,\n\nGDG on Campus — SRM University AP presents the Google Solution Hunt Challenge 2026!\n\nA one-day hands-on technology sprint focusing on solving UN Sustainable Development Goals using Google Cloud, Gemini, and Android tools.\n\nVENUE:\nX-Lab Auditorium, SRM University AP\nMangalagiri Neerukonda Tadikonda Road, Mangalagiri, AP - 522240\n\nDATE & TIME:\nSeptember 29, 2026 · 9:00 AM – 5:30 PM\n\nGDG on Campus Team\nSRM University-AP`,
    timestamp: "2026-09-26T10:00:00.000Z",
    dateFormatted: "Sep 26, 2026 · 10:00 AM",
    category: "HACKATHONS",
    priority: "MEDIUM",
    priorityScore: 68,
    priorityReason: "One-day flagship hackathon challenge hosted at X-Lab Auditorium.",
    categoryReason: "Google Developer Groups student community event and hackathon.",
    summary: "GDG Google Solution Hunt Challenge at X-Lab Auditorium on Sept 29.",
    actionRequired: true,
    actionText: "Register team for Google Solution Hunt Challenge before slot fill",
    actionDeadline: "Sep 28, 2026 · 6:00 PM",
    deadlineDate: "2026-09-28T12:30:00.000Z",
    eventDate: "2026-09-29T03:30:00.000Z",
    location: "X-Lab Auditorium, Neerukonda",
    affectedGroup: "All Developers & Engineering Students",
    urgency: "MEDIUM",
    tags: ["gdg", "hackathon", "google-solution-hunt", "x-lab", "gemini"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-gdg-hunt"
  },

  // 9. TRANSPORT DELAY VIA BYPASS (HIGH)
  {
    id: "email-srm-009",
    sender: "transport@srmap.edu.in",
    senderName: "Transport Operations Cell, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "Transport Notice: Route 5 & 8 Delayed (Rerouted via Mangalagiri Bypass)",
    body: `Dear Student Commuters,\n\nDue to sudden culvert repair work on the Neerukonda-Tadikonda rural corridor, University Bus Routes 5 and 8 will operate on an adjusted morning schedule:\n\n- Departure Time: Shifted 15 minutes earlier (7:25 AM instead of 7:40 AM)\n- Route: Diverted via Mangalagiri Bypass highway\n- Drop-off Point: Main Gate Bus Bay 2\n\nStudents appearing for 9:00 AM examinations are advised to board the earlier transit shuttle.\n\nTransport Cell\nSRM University-AP`,
    timestamp: "2026-09-29T06:10:00.000Z",
    dateFormatted: "Sep 29, 2026 · 6:10 AM",
    category: "TRANSPORT",
    priority: "HIGH",
    priorityScore: 80,
    priorityReason: "Morning bus delay and 15-minute earlier departure; impacts arrival for 9 AM exams.",
    categoryReason: "Campus transit route diversion and morning shuttle timing revision.",
    summary: "Bus Routes 5 & 8 departing 15 mins earlier (7:25 AM) via Mangalagiri Bypass to Main Gate Bay 2.",
    actionRequired: true,
    actionText: "Board university bus at earlier 7:25 AM time to reach campus for 9 AM exams",
    actionDeadline: "Tomorrow, 7:25 AM",
    deadlineDate: "2026-09-30T01:55:00.000Z",
    location: "Main Gate Bus Bay 2",
    affectedGroup: "Routes 5 & 8 Student Day Scholars",
    urgency: "HIGH",
    tags: ["transport", "bus-route", "delay", "mangalagiri-bypass", "transit"],
    isRead: false,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-transport-transit"
  },

  // 10. CSE EXPERT TALK: SECURING AUTONOMOUS AI PLATFORMS (HIGH)
  {
    id: "email-srm-010",
    sender: "hod.cse@srmap.edu.in",
    senderName: "Department of CSE, SEAS",
    recipient: "demo.student@srmap.edu.in",
    cc: ["dean.seas@srmap.edu.in"],
    subject: "CSE Expert Talk: 'Human in the Loop is Not Enough – Securing Autonomous AI Platforms'",
    body: `Dear CSE & AI/ML Students,\n\nThe Department of Computer Science and Engineering invites you to a distinguished technical session:\n\nTITLE: 'Human in the Loop is Not Enough – Real Lessons from Securing an Autonomous AI Platform'\nDATE: Saturday, September 26, 2026\nTIME: 11:00 AM – 12:30 PM (IST)\nMODE: Online (Google Meet link provided upon registration)\n\nKEY TOPICS:\n- Enterprise AI Governance & Autonomous Agent Vulnerabilities\n- Threat Modelling for LLM Workflows\n- AI-Specific Penetration Testing\n- OWASP Top 10 for LLM Applications & Agentic AI Security\n\nSpeaker: Global Principal AI Security Architect.\n\nAttendance is mandatory for B.Tech CSE (AI & ML track) Semester 3 students.\n\nDepartment of CSE\nSchool of Engineering and Sciences, SRM University-AP`,
    timestamp: "2026-09-24T08:00:00.000Z",
    dateFormatted: "Sep 24, 2026 · 8:00 AM",
    category: "TECH EVENTS",
    priority: "HIGH",
    priorityScore: 85,
    priorityReason: "Mandatory expert talk on Autonomous AI Platform security with OWASP Top 10 for AI.",
    categoryReason: "High-value academic expert talk for CSE AI/ML specialisation.",
    summary: "CSE Expert Talk on Securing Autonomous AI Platforms on Sep 26, 11 AM - 12:30 PM.",
    actionRequired: true,
    actionText: "Attend CSE Expert Talk online on Sep 26 at 11:00 AM",
    actionDeadline: "Sep 26, 2026 · 11:00 AM",
    deadlineDate: "2026-09-26T05:30:00.000Z",
    eventDate: "2026-09-26T05:30:00.000Z",
    location: "Online (Google Meet)",
    affectedGroup: "B.Tech CSE (AI & ML) Students",
    urgency: "HIGH",
    tags: ["expert-talk", "cse", "ai-security", "owasp", "agentic-ai", "seas"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-ai-talk",
    relatedCalendarEventId: "cal-srm-003"
  },

  // 11. EARLY CLOSURE (SEPTEMBER 24, 3 PM) (HIGH)
  {
    id: "email-srm-011",
    sender: "registrar.office@srmap.edu.in",
    senderName: "Registrar Office, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "URGENT CIRCULAR: Early Campus Closure Today at 3:00 PM due to Rain",
    body: `URGENT NOTICE TO ALL FACULTY, STAFF, AND STUDENTS:\n\nDue to relentless heavy downpours resulting in severe water accumulation along Neerukonda connecting roads, the university will close early today, September 24, 2026, at 3:00 PM.\n\nAll instructional classes and practical laboratories scheduled after 3:00 PM stand cancelled.\n\nTRANSPORT SCHEDULE CHANGE:\nAll university buses will depart campus bus bays at 3:15 PM sharp instead of the usual 5:45 PM.\n\nDay scholars are advised to proceed to the bus parking area immediately upon class dismissal.\n\nRegistrar Office\nSRM University-AP, Andhra Pradesh`,
    timestamp: "2026-09-24T07:15:00.000Z",
    dateFormatted: "Sep 24, 2026 · 12:45 PM",
    category: "EMERGENCY",
    priority: "CRITICAL",
    priorityScore: 96,
    priorityReason: "Emergency early campus closure at 3:00 PM; buses depart at 3:15 PM instead of 5:45 PM.",
    categoryReason: "Urgent emergency administrative circular and transit schedule shift.",
    summary: "University closes early at 3 PM today due to rain. Buses depart at 3:15 PM sharp instead of 5:45 PM.",
    actionRequired: true,
    actionText: "Board university buses at 3:15 PM today; after-3 PM classes cancelled",
    actionDeadline: "Today, 3:15 PM",
    deadlineDate: "2026-09-24T09:45:00.000Z",
    location: "Campus Bus Bays",
    affectedGroup: "All SRM AP Students & Staff",
    urgency: "CRITICAL",
    tags: ["early-closure", "rain", "emergency", "bus-timing", "registrar"],
    isRead: true,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-early-closure"
  },

  // 12. AGENTIC AI HACKATHON (ZIRO.DIGITAL) (MEDIUM)
  {
    id: "email-srm-012",
    sender: "ecell@srmap.edu.in",
    senderName: "Directorate of Entrepreneurship & Innovation",
    recipient: "demo.student@srmap.edu.in",
    subject: "Agentic AI Hackathon 2026 by Ziro.Digital — ₹50,000 Prize Pool",
    body: `Dear Innovators,\n\nSRM University-AP partners with Ziro.Digital to launch the Agentic AI Hackathon 2026!\n\nBuild autonomous agents, multi-agent frameworks, and workflow automation solutions.\n\nTIMELINE:\n- Registration Deadline: October 16, 2026\n- Online Build & Jury Round: October 18 – 26, 2026\n- Grand Finale: October 31, 2026 (Hyderabad)\n- Total Cash Prize: ₹50,000 + Incubation Mentorship\n\nTeams of 2 to 4 students from CSE, AI/ML, and ECE are encouraged to register.\n\nDirectorate of Entrepreneurship & Innovation\nSRM University-AP`,
    timestamp: "2026-09-27T11:30:00.000Z",
    dateFormatted: "Sep 27, 2026 · 11:30 AM",
    category: "HACKATHONS",
    priority: "MEDIUM",
    priorityScore: 66,
    priorityReason: "External nationwide Agentic AI hackathon with ₹50,000 prize pool.",
    categoryReason: "Entrepreneurship and technical innovation hackathon challenge.",
    summary: "Agentic AI Hackathon by Ziro.Digital: Registrations open until Oct 16, Finale Oct 31 in Hyderabad.",
    actionRequired: true,
    actionText: "Form team and register for Agentic AI Hackathon before Oct 16",
    actionDeadline: "Oct 16, 2026 · 11:59 PM",
    deadlineDate: "2026-10-16T18:29:00.000Z",
    location: "Online / Grand Finale Hyderabad",
    affectedGroup: "CSE & AI/ML Students",
    urgency: "MEDIUM",
    tags: ["hackathon", "agentic-ai", "ziro-digital", "cash-prize", "hyderabad"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-agentic-hackathon"
  },

  // 13. CYBER SECURITY FDP (MEDIUM)
  {
    id: "email-srm-013",
    sender: "dean.seas@srmap.edu.in",
    senderName: "School of Engineering and Sciences (SEAS)",
    recipient: "demo.student@srmap.edu.in",
    subject: "Cyber Security Faculty & Student Development Programme (Oct 5–9, 2026)",
    body: `Dear Engineering Students & Researchers,\n\nSEAS announces a 5-day National Level Programme on 'Applied Cyber Security, Network Forensics & Cloud Defense'.\n\nSCHEDULE:\n- Dates: October 5 – 9, 2026\n- Daily Sessions: 10:00 AM – 12:00 PM & 2:30 PM – 4:30 PM\n- Mode: Online Synchronous\n- Registration Cutoff: October 5, 2026, 9:00 AM\n\nCertificate of Completion will be issued based on 80% minimum attendance and submission of daily lab feedback.\n\nDean, School of Engineering and Sciences\nSRM University-AP, Andhra Pradesh`,
    timestamp: "2026-09-26T15:00:00.000Z",
    dateFormatted: "Sep 26, 2026 · 3:00 PM",
    category: "ACADEMICS",
    priority: "MEDIUM",
    priorityScore: 62,
    priorityReason: "5-day national technical certification programme in cyber security with attendance requirement.",
    categoryReason: "Academic faculty and student professional development programme.",
    summary: "Cyber Security Development Programme from Oct 5–9. Register before Oct 5, 9:00 AM.",
    actionRequired: true,
    actionText: "Register for Cyber Security Programme before Oct 5 9:00 AM",
    actionDeadline: "Oct 5, 2026 · 9:00 AM",
    deadlineDate: "2026-10-05T03:30:00.000Z",
    location: "Online Synchronous",
    affectedGroup: "B.Tech CSE & ECE Students",
    urgency: "MEDIUM",
    tags: ["cyber-security", "fdp", "seas", "certification", "forensics"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-cyber-fdp"
  },

  // 14. TERRATHON 2026 SUSTAINABILITY HACKATHON (HIGH)
  {
    id: "email-srm-014",
    sender: "communications@srmap.edu.in",
    senderName: "Directorate of Communications",
    recipient: "demo.student@srmap.edu.in",
    subject: "Terrathon 2026: Sustainability Hackathon Opening Ceremony",
    body: `Dear SRM AP Campus Community,\n\nThe Department of Environmental Science and Engineering, in coordination with the Student Council, invites you to Terrathon 2026:\n\nVENUE: APJ Abdul Kalam Auditorium, Administrative Block\nDATE: Saturday, September 26, 2026\nTIME: 10:00 AM – 11:00 AM (Opening Ceremony)\n\nInnovate solutions for water conservation in Amaravati, solar microgrid optimization, and electronic waste recycling on campus.\n\nCash prizes and university sustainability commendations will be awarded to the top 3 teams.\n\nDirectorate of Communications\nSRM University-AP`,
    timestamp: "2026-09-23T10:00:00.000Z",
    dateFormatted: "Sep 23, 2026 · 10:00 AM",
    category: "EVENTS",
    priority: "HIGH",
    priorityScore: 78,
    priorityReason: "Major sustainability hackathon in APJ Abdul Kalam Auditorium with cash awards.",
    categoryReason: "Campus innovation hackathon and environmental symposium.",
    summary: "Terrathon 2026 Sustainability Hackathon on Sep 26, 10–11 AM at APJ Abdul Kalam Auditorium.",
    actionRequired: true,
    actionText: "Assemble at APJ Abdul Kalam Auditorium by 9:45 AM for Terrathon kickoff",
    actionDeadline: "Sep 26, 2026 · 9:45 AM",
    deadlineDate: "2026-09-26T04:15:00.000Z",
    eventDate: "2026-09-26T04:30:00.000Z",
    location: "APJ Abdul Kalam Auditorium",
    affectedGroup: "All SRM AP Students",
    urgency: "HIGH",
    tags: ["terrathon", "sustainability", "hackathon", "auditorium", "green-campus"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-terrathon",
    relatedCalendarEventId: "cal-srm-004"
  },

  // 15. GOOGLE CLASSROOM: AI TOOLS & PROMPT ENGINEERING QUIZ (HIGH)
  {
    id: "email-srm-015",
    sender: "classroom-notice@srmap.edu.in",
    senderName: "Google Classroom — AI Tools & Prompt Engineering Club",
    recipient: "demo.student@srmap.edu.in",
    subject: "Classroom Notice: Offline AI Quiz (30 Questions) in CV 704 on Sep 30",
    body: `[Posted in Google Classroom: AI Tools & Prompt Engineering Club]\n\nDear Members,\n\nThe mid-semester offline AI Quiz is scheduled:\n\n- Date: Wednesday, September 30, 2026\n- Time: 3:00 PM – 5:00 PM\n- Venue: Room CV 704, Central Academic Wing\n- Format: 30 Questions (Pen and Paper, Multiple Choice & Short Reasoning)\n\nRULES:\n- Strictly NO AI tools, ChatGPT, Claude, online search, or messaging allowed.\n- Individual participation only. Sharing answers leads to disqualification.\n- Exciting prizes for the Top 3 scorers!\n\nFaculty Advisor\nAI Tools & Prompt Engineering Club, SRM AP`,
    timestamp: "2026-09-28T16:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 4:00 PM",
    category: "ASSIGNMENTS",
    priority: "HIGH",
    priorityScore: 84,
    priorityReason: "Classroom offline proctored quiz tomorrow in CV 704; strict no-AI rule.",
    categoryReason: "Classroom coursework evaluation and offline quiz.",
    summary: "Offline AI Quiz (30 questions) on Sept 30, 3–5 PM in Room CV 704. No AI tools permitted.",
    actionRequired: true,
    actionText: "Report to Room CV 704 by 2:50 PM for offline AI Quiz",
    actionDeadline: "Sep 30, 2026 · 2:50 PM",
    deadlineDate: "2026-09-30T09:20:00.000Z",
    eventDate: "2026-09-30T09:30:00.000Z",
    location: "CV 704, Central Academic Wing",
    affectedGroup: "AI Tools Club Enrolled Students",
    urgency: "HIGH",
    tags: ["google-classroom", "quiz", "ai-tools", "cv-704", "proctored"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-classroom-quiz",
    relatedClassroomWorkId: "work-1"
  },

  // 16. CSE EXPERT TALK REMINDER & MEETING LINK (thread with 010) (HIGH)
  {
    id: "email-srm-016",
    sender: "hod.cse@srmap.edu.in",
    senderName: "Department of CSE, SEAS",
    recipient: "demo.student@srmap.edu.in",
    subject: "REMINDER: Joining Link for AI Security Expert Talk Tomorrow at 11 AM",
    body: `Dear Students,\n\nThis is a reminder for tomorrow's CSE Expert Talk on 'Human in the Loop is Not Enough – Securing Autonomous AI Platforms'.\n\nSESSION LINK:\nhttps://meet.google.com/srm-seas-csec\nTime: 11:00 AM – 12:30 PM\n\nPlease join with your institutional @srmap.edu.in account 5 minutes before start for attendance logging.\n\nDepartment of CSE, SRM AP`,
    timestamp: "2026-09-25T14:00:00.000Z",
    dateFormatted: "Sep 25, 2026 · 2:00 PM",
    category: "TECH EVENTS",
    priority: "HIGH",
    priorityScore: 76,
    priorityReason: "Reminder with live Google Meet credentials for mandatory AI security session.",
    categoryReason: "Follow-up meeting access communication.",
    summary: "Reminder: Join AI Security Expert Talk tomorrow at 11 AM via Google Meet with @srmap.edu.in email.",
    actionRequired: true,
    actionText: "Join Google Meet at 10:55 AM tomorrow for AI Security Talk",
    actionDeadline: "Sep 26, 2026 · 10:55 AM",
    deadlineDate: "2026-09-26T05:25:00.000Z",
    location: "Google Meet",
    affectedGroup: "B.Tech CSE (AI & ML) Students",
    urgency: "HIGH",
    tags: ["expert-talk", "meet-link", "cse", "reminder"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-ai-talk"
  },

  // 17. EARLY CLOSURE BUS BAY CONFIRMATION (thread with 011) (HIGH)
  {
    id: "email-srm-017",
    sender: "transport@srmap.edu.in",
    senderName: "Transport Operations Cell",
    recipient: "demo.student@srmap.edu.in",
    subject: "URGENT UPDATE: 3:15 PM Early Departure Bus Bay Allocations",
    body: `ATTENTION ALL COMMUTERS:\n\nFollowing the 3:00 PM campus closure announcement, all transit buses are parked at the Main Gate Terminal:\n\n- Bay 1 to 4: Vijayawada & Benz Circle\n- Bay 5 to 7: Guntur & Mangalagiri Bypass\n- Bay 8: Tenali & Amaravati Rural\n\nAll shuttles will leave at 3:15 PM sharp.\n\nTransport Cell, SRM University-AP`,
    timestamp: "2026-09-24T07:45:00.000Z",
    dateFormatted: "Sep 24, 2026 · 1:15 PM",
    category: "TRANSPORT",
    priority: "CRITICAL",
    priorityScore: 95,
    priorityReason: "Terminal bay allocation for immediate 3:15 PM rain departure.",
    categoryReason: "Emergency bus bay boarding plan.",
    summary: "Bus bays 1–8 designated for 3:15 PM early departure across Vijayawada, Guntur, and Tenali routes.",
    actionRequired: true,
    actionText: "Proceed to assigned Main Gate Bus Bay before 3:15 PM departure",
    actionDeadline: "Today, 3:15 PM",
    deadlineDate: "2026-09-24T09:45:00.000Z",
    location: "Main Gate Bus Bays",
    affectedGroup: "All Day Scholar Bus Commuters",
    urgency: "CRITICAL",
    tags: ["transport", "bus-bay", "early-departure", "rain"],
    isRead: true,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-early-closure"
  },

  // 18. ACM RECRUITMENT REMINDER (thread with 005) (MEDIUM)
  {
    id: "email-srm-018",
    sender: "acm.core@srmap.edu.in",
    senderName: "ACM Student Chapter, SRM AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "REMINDER: ACM Recruitment Closes Tomorrow Night!",
    body: `Hello Tech Community,\n\nOnly 24 hours left to submit your application for the ACM Student Chapter Core Committee!\n\nApplications close: Wednesday, September 30, at 11:59 PM.\n\nShortlisted candidates will receive interview slots for Oct 3.\n\nACM Student Chapter, SRM AP`,
    timestamp: "2026-09-29T10:00:00.000Z",
    dateFormatted: "Sep 29, 2026 · 10:00 AM",
    category: "STUDENT CLUBS",
    priority: "MEDIUM",
    priorityScore: 68,
    priorityReason: "Final 24-hour reminder to complete ACM Chapter recruitment application.",
    categoryReason: "Club recruitment deadline reminder.",
    summary: "Final 24-hour reminder: ACM Core Committee applications close tomorrow night at 11:59 PM.",
    actionRequired: true,
    actionText: "Complete ACM application form before Sept 30 11:59 PM",
    actionDeadline: "Tomorrow, 11:59 PM",
    deadlineDate: "2026-09-30T18:29:00.000Z",
    location: "Online Portal",
    affectedGroup: "SEAS Students",
    urgency: "MEDIUM",
    tags: ["acm", "deadline-reminder", "recruitment"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-acm-recruitment"
  },

  // 19. TERRATHON PROBLEM STATEMENTS (thread with 014) (MEDIUM)
  {
    id: "email-srm-019",
    sender: "communications@srmap.edu.in",
    senderName: "Directorate of Communications",
    recipient: "demo.student@srmap.edu.in",
    subject: "Terrathon 2026: Official Problem Statements & Evaluation Rubric",
    body: `Dear Terrathon Participants,\n\nThe 4 problem statement tracks for Terrathon 2026 have been published:\n\n1. AI-Powered Smart Micro-Irrigation for Andhra Pradesh Farmers\n2. Real-Time Water Quality Monitoring Sensor Network\n3. Zero-Waste Mess Food Composting Optimization\n4. E-Waste Tracking using Decentralized Ledgers\n\nSubmissions open on the hackathon portal at 11:00 AM following the opening ceremony.\n\nDepartment of Environmental Science & Engineering, SRM AP`,
    timestamp: "2026-09-25T11:00:00.000Z",
    dateFormatted: "Sep 25, 2026 · 11:00 AM",
    category: "EVENTS",
    priority: "MEDIUM",
    priorityScore: 70,
    priorityReason: "Problem statement tracks released for Terrathon sustainability competition.",
    categoryReason: "Event track release notice.",
    summary: "Terrathon 2026 problem statements released covering smart irrigation, water quality, and e-waste.",
    actionRequired: true,
    actionText: "Select problem statement track and register team members",
    actionDeadline: "Sep 26, 2026 · 11:30 AM",
    deadlineDate: "2026-09-26T06:00:00.000Z",
    location: "APJ Abdul Kalam Auditorium",
    affectedGroup: "Terrathon Participants",
    urgency: "MEDIUM",
    tags: ["terrathon", "problem-statements", "sustainability"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-terrathon"
  },

  // 20. GOOGLE CLASSROOM: CSE 204 ASSIGNMENT 2 (HIGH)
  {
    id: "email-srm-020",
    sender: "classroom-notice@srmap.edu.in",
    senderName: "Google Classroom — CSE 204 Algorithms",
    recipient: "demo.student@srmap.edu.in",
    subject: "Assignment Posted: 'Assignment 2: Dynamic Programming & Greedy Strategies'",
    body: `[Google Classroom Notification: CSE 204 - Design and Analysis of Algorithms]\n\nDr. Murali Krishna posted a new assignment:\n\n'Assignment 2: Dynamic Programming & Greedy Strategies'\nDue Date: Saturday, October 3, 2026 at 11:59 PM.\n\nImplement solution algorithms for 0/1 Knapsack, Longest Common Subsequence, and Huffman Coding with empirical asymptotic performance charts. Submit PDF and GitHub repo link.\n\nMaximum Points: 50`,
    timestamp: "2026-09-28T18:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 6:00 PM",
    category: "ASSIGNMENTS",
    priority: "HIGH",
    priorityScore: 82,
    priorityReason: "Core academic coursework assignment with deadline on October 3.",
    categoryReason: "Google Classroom coursework release.",
    summary: "CSE 204 Assignment 2 on Dynamic Programming posted. Due Oct 3, 11:59 PM.",
    actionRequired: true,
    actionText: "Complete and submit CSE 204 Assignment 2 on Google Classroom",
    actionDeadline: "Oct 3, 2026 · 11:59 PM",
    deadlineDate: "2026-10-03T18:29:00.000Z",
    location: "Google Classroom Portal",
    affectedGroup: "B.Tech CSE Semester 3",
    urgency: "HIGH",
    tags: ["google-classroom", "cse204", "assignment", "algorithms", "dynamic-programming"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-cse204-classroom",
    relatedClassroomWorkId: "work-2"
  },

  // 21. GOOGLE CLASSROOM: MDS 250 AI COURSE QUIZ (MEDIUM)
  {
    id: "email-srm-021",
    sender: "classroom-notice@srmap.edu.in",
    senderName: "Google Classroom — MDS 250 Do Machines Think",
    recipient: "demo.student@srmap.edu.in",
    subject: "Classroom Announcement: MDS 250 Quiz 1 Scheduled for Oct 4",
    body: `[Posted in Google Classroom: MDS 250 - Do Machines Think: An Introduction to AI]\n\nDear Students,\n\nQuiz 1 covering Module 1 (Foundations of Cognitive Systems & Turing Tests) will be held online via LMS on Sunday, October 4, 2026, from 7:00 PM to 8:00 PM.\n\nTotal Questions: 25\nWeightage: 10% of continuous assessment.\n\nDr. Priya Ramanathan\nCourse Instructor`,
    timestamp: "2026-09-27T09:30:00.000Z",
    dateFormatted: "Sep 27, 2026 · 9:30 AM",
    category: "ACADEMICS",
    priority: "MEDIUM",
    priorityScore: 72,
    priorityReason: "Continuous assessment online quiz on October 4 with 10% course weightage.",
    categoryReason: "Academic course assessment announcement.",
    summary: "MDS 250 Quiz 1 scheduled on LMS for Sunday, Oct 4, from 7:00 PM to 8:00 PM.",
    actionRequired: true,
    actionText: "Prepare Module 1 notes and take MDS 250 Quiz 1 on Oct 4",
    actionDeadline: "Oct 4, 2026 · 7:00 PM",
    deadlineDate: "2026-10-04T13:30:00.000Z",
    eventDate: "2026-10-04T13:30:00.000Z",
    location: "Online LMS Portal",
    affectedGroup: "MDS 250 Enrolled Students",
    urgency: "MEDIUM",
    tags: ["google-classroom", "mds250", "quiz", "ai-intro", "turing-test"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-mds250"
  },

  // 22. TUITION FEE DEADLINE (HIGH)
  {
    id: "email-srm-022",
    sender: "fees.office@srmap.edu.in",
    senderName: "Finance & Accounts Office, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "Tuition Fee Installment Payment Deadline (Without Fine: Oct 5, 2026)",
    body: `Dear Student,\n\nThis is to remind you that the last date for the payment of the Odd Semester 2026-27 tuition and hostel fee installment without late fee is Monday, October 5, 2026.\n\nA late surcharge of ₹250 per day will apply starting October 6.\n\nPlease remit fees online at https://fees.srmap.edu.in and retain the digital transaction receipt.\n\nFinance & Accounts Directorate\nSRM University-AP`,
    timestamp: "2026-09-26T12:00:00.000Z",
    dateFormatted: "Sep 26, 2026 · 12:00 PM",
    category: "FEES",
    priority: "HIGH",
    priorityScore: 84,
    priorityReason: "Fee payment deadline on Oct 5; late penalty surcharge of ₹250/day from Oct 6.",
    categoryReason: "University financial accounts installment notification.",
    summary: "Tuition fee installment due by Oct 5 without fine. ₹250/day late penalty from Oct 6.",
    actionRequired: true,
    actionText: "Pay semester fee balance on fees.srmap.edu.in before Oct 5",
    actionDeadline: "Monday, Oct 5, 2026 · 5:00 PM",
    deadlineDate: "2026-10-05T11:30:00.000Z",
    location: "Online Fee Portal",
    affectedGroup: "All Students with Outstanding Balances",
    urgency: "HIGH",
    tags: ["fees", "tuition", "late-fee", "finance", "portal"],
    isRead: false,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-fees-notice"
  },

  // 23. CENTRAL LIBRARY 24/7 OPENING (MEDIUM)
  {
    id: "email-srm-023",
    sender: "library@srmap.edu.in",
    senderName: "Central Library, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "Central Library Operating 24/7 for Mid-Semester Exam Period",
    body: `Dear Students and Researchers,\n\nTo facilitate focused preparation for mid-semester evaluations, the Central Library will operate 24 hours a day, 7 days a week, from September 28 to October 12, 2026.\n\n- Silent Study Zones: 2nd and 3rd Floors\n- Collaborative Discussion Hub: Ground Floor Café\n- Wi-Fi and power strips available at all desks\n\nCarry your student smart ID card for post-10 PM biometric access.\n\nChief Librarian\nCentral Library, SRM University-AP`,
    timestamp: "2026-09-27T14:00:00.000Z",
    dateFormatted: "Sep 27, 2026 · 2:00 PM",
    category: "LIBRARY",
    priority: "MEDIUM",
    priorityScore: 52,
    priorityReason: "Extended 24/7 library operating hours for exam season.",
    categoryReason: "Campus academic facility hours update.",
    summary: "Central Library open 24/7 from Sept 28 to Oct 12 for exam study. Carry ID for entry after 10 PM.",
    actionRequired: false,
    location: "Central Library Building",
    affectedGroup: "All SRM AP Students",
    urgency: "MEDIUM",
    tags: ["library", "24-7", "exam-prep", "study-hall"],
    isRead: true,
    source: "demo",
    systemOrigin: "Campus Location",
    threadId: "thread-library"
  },

  // 24. HOSTEL BLOCK WATER SUPPLY TIMINGS (LOW)
  {
    id: "email-srm-024",
    sender: "hostel.office@srmap.edu.in",
    senderName: "Hostel Administration & Facilities",
    recipient: "demo.student@srmap.edu.in",
    subject: "Circular: Scheduled Maintenance of Overhead Solar Water Heaters",
    body: `Dear Hostel Residents,\n\nScheduled maintenance and descaling of overhead solar water heating systems will be carried out across Ganga, Yamuna, and Krishna Hostels on Thursday, October 1, between 10:00 AM and 2:00 PM.\n\nNormal water supply will remain uninterrupted. Hot water supply will resume by 4:00 PM.\n\nChief Warden\nHostel Administration, SRM University-AP`,
    timestamp: "2026-09-28T11:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 11:00 AM",
    category: "HOSTEL",
    priority: "LOW",
    priorityScore: 35,
    priorityReason: "Scheduled solar heater maintenance in hostel blocks without water disruption.",
    categoryReason: "Hostel maintenance notice.",
    summary: "Solar water heater maintenance in Ganga, Yamuna, Krishna hostels on Oct 1, 10 AM - 2 PM.",
    actionRequired: false,
    location: "Student Hostel Blocks",
    affectedGroup: "Hostel Residents",
    urgency: "LOW",
    tags: ["hostel", "maintenance", "solar-water", "warden"],
    isRead: true,
    source: "demo",
    systemOrigin: "Campus Location",
    threadId: "thread-hostel-maintenance"
  },

  // 25. PLACEMENTS: PRE-PLACEMENT TALK (HIGH)
  {
    id: "email-srm-025",
    sender: "placements@srmap.edu.in",
    senderName: "Career Review & Competence Studio (CR&CS)",
    recipient: "demo.student@srmap.edu.in",
    subject: "Placement Alert: Google Cloud & Microsoft Summer Internship Briefing",
    body: `Dear Engineering Students,\n\nThe Career Review and Competence Studio (CR&CS) is hosting an exclusive pre-internship briefing for Summer 2027 technical engineering internships.\n\nDATE: Friday, October 2, 2026\nTIME: 5:30 PM – 7:00 PM\nVENUE: X-Lab Auditorium\n\nELIGIBILITY:\n- Minimum CGPA of 8.0 with no active standing backlogs\n- Enrolled in B.Tech CSE, AI/ML, or ECE\n\nResume uploads on the CR&CS Superset portal close Saturday at 12:00 PM.\n\nDirector, CR&CS\nSRM University-AP`,
    timestamp: "2026-09-28T17:30:00.000Z",
    dateFormatted: "Sep 28, 2026 · 5:30 PM",
    category: "PLACEMENTS",
    priority: "HIGH",
    priorityScore: 86,
    priorityReason: "High-stakes corporate internship briefing for Google & Microsoft with CGPA 8.0 cutoff.",
    categoryReason: "Official corporate placement and career recruitment drive.",
    summary: "Pre-internship briefing for Google Cloud & Microsoft on Oct 2, 5:30 PM at X-Lab Auditorium.",
    actionRequired: true,
    actionText: "Upload updated ATS resume on CR&CS Superset portal before Saturday noon",
    actionDeadline: "Saturday, Oct 3, 2026 · 12:00 PM",
    deadlineDate: "2026-10-03T06:30:00.000Z",
    eventDate: "2026-10-02T12:00:00.000Z",
    location: "X-Lab Auditorium",
    affectedGroup: "CSE & ECE Students (CGPA 8.0+)",
    urgency: "HIGH",
    tags: ["placements", "crcs", "internships", "google-cloud", "microsoft", "x-lab"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-placements-intern"
  },

  // 26. CSE 213 JAVA LAB EXAM (HIGH)
  {
    id: "email-srm-026",
    sender: "hod.cse@srmap.edu.in",
    senderName: "Department of CSE, SEAS",
    recipient: "demo.student@srmap.edu.in",
    subject: "CSE 213: Advanced Java Programming Lab Exam Slots Announced",
    body: `Dear B.Tech CSE Semester 3 Students,\n\nThe continuous evaluation practical exam for CSE 213 (Advanced Java Programming) will take place across Computing Labs 1, 2, and 3:\n\n- Batch 1 (Reg 1 to 40): Thursday, Oct 1, 9:00 AM – 11:30 AM (Computing Lab 1)\n- Batch 2 (Reg 41 to 80): Thursday, Oct 1, 1:30 PM – 4:00 PM (Computing Lab 2)\n\nTasks will involve JDBC Connectivity, Multithreading, and Spring Boot REST API development.\n\nSigned lab record sheets must be presented before login.\n\nCSE Department\nSRM University-AP`,
    timestamp: "2026-09-28T13:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 1:00 PM",
    category: "EXAMS",
    priority: "HIGH",
    priorityScore: 85,
    priorityReason: "Continuous evaluation practical exam in Advanced Java on October 1.",
    categoryReason: "Department practical laboratory examination schedule.",
    summary: "CSE 213 Advanced Java lab exam scheduled for Oct 1 in Computing Labs 1 & 2.",
    actionRequired: true,
    actionText: "Submit Java lab record signed sheets before Thursday practical exam",
    actionDeadline: "Oct 1, 2026 · 9:00 AM",
    deadlineDate: "2026-10-01T03:30:00.000Z",
    location: "Computing Labs 1 & 2, SR Block",
    affectedGroup: "CSE Semester 3 Students",
    urgency: "HIGH",
    tags: ["java", "cse213", "lab-exam", "practical", "spring-boot"],
    isRead: false,
    source: "demo",
    systemOrigin: "Exam System",
    threadId: "thread-java-lab"
  },

  // 27. FIC 120 REMEDIAL TUTORIAL (MEDIUM)
  {
    id: "email-srm-027",
    sender: "dean.seas@srmap.edu.in",
    senderName: "School of Engineering and Sciences",
    recipient: "demo.student@srmap.edu.in",
    subject: "FIC 120: Foundations of EEE — Remedial Problem Solving Clinics",
    body: `Dear Students,\n\nSpecial remedial tutorial clinics for FIC 120 (Foundations of Electrical and Electronics Engineering) will be conducted by senior teaching fellows:\n\n- Topics: Thevenin Equivalent Circuits, AC Phasors, Operational Amplifiers\n- Schedule: Every Tuesday and Thursday, 5:00 PM – 6:15 PM\n- Venue: Room S104, SR Block\n\nStudents who scored below 60% in Mid-Term Quiz 1 are strongly advised to attend.\n\nSEAS Academic Cell\nSRM University-AP`,
    timestamp: "2026-09-27T16:00:00.000Z",
    dateFormatted: "Sep 27, 2026 · 4:00 PM",
    category: "ACADEMICS",
    priority: "MEDIUM",
    priorityScore: 60,
    priorityReason: "Remedial tutorial sessions for EEE circuit analysis in SR Block.",
    categoryReason: "Academic remedial clinic and tutorial support.",
    summary: "FIC 120 EEE remedial clinics every Tuesday & Thursday at 5 PM in Room S104, SR Block.",
    actionRequired: false,
    location: "Room S104, SR Block",
    affectedGroup: "Students enrolled in FIC 120",
    urgency: "MEDIUM",
    tags: ["eee", "fic120", "remedial", "tutorial", "circuits"],
    isRead: true,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-eee-remedial"
  },

  // 28. SCHOLARSHIP PORTAL REOPENED (HIGH)
  {
    id: "email-srm-028",
    sender: "scholarships@srmap.edu.in",
    senderName: "Office of Student Financial Aid",
    recipient: "demo.student@srmap.edu.in",
    subject: "National Merit-cum-Means Scholarship Portal Re-Opened until Oct 8",
    body: `Dear Eligible Students,\n\nBy directive of the State Higher Education Department, the National Merit-cum-Means (NMM) scholarship verification portal has been re-opened for Andhra Pradesh university scholars.\n\nDEADLINE:\nThursday, October 8, 2026, at 5:00 PM.\n\nSubmit verified family income certificates and semester grade transcripts to Financial Aid Desk, Room 202, Admin Block.\n\nFinancial Aid Office\nSRM University-AP`,
    timestamp: "2026-09-28T10:30:00.000Z",
    dateFormatted: "Sep 28, 2026 · 10:30 AM",
    category: "SCHOLARSHIPS",
    priority: "HIGH",
    priorityScore: 82,
    priorityReason: "Reopened financial aid portal with direct tuition scholarship disbursal until Oct 8.",
    categoryReason: "Student financial aid and national scholarship opportunity.",
    summary: "National Merit scholarship portal re-opened until Oct 8. Submit documents to Room 202 Admin Block.",
    actionRequired: true,
    actionText: "Submit verified grade transcripts to Financial Aid Cell Room 202",
    actionDeadline: "Oct 8, 2026 · 5:00 PM",
    deadlineDate: "2026-10-08T11:30:00.000Z",
    location: "Room 202, Administrative Block",
    affectedGroup: "Scholarship Eligible Students",
    urgency: "HIGH",
    tags: ["scholarship", "merit", "financial-aid", "room-202"],
    isRead: false,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-scholarship"
  },

  // 29. STUDENT COUNCIL ELECTIONS (LOW)
  {
    id: "email-srm-029",
    sender: "studentaffairs@srmap.edu.in",
    senderName: "Directorate of Student Affairs (DSA)",
    recipient: "demo.student@srmap.edu.in",
    subject: "Student Council Elections 2026-27: Nomination Guidelines & Code of Conduct",
    body: `Dear Students,\n\nThe Directorate of Student Affairs invites nominations for the Student Council 2026-27:\n\n- Posts: President, Vice-President, General Secretary, Academic Representative (SEAS)\n- Eligibility: Minimum CGPA 7.5, zero disciplinary infractions\n- Nomination Window: October 12 – 15, 2026\n\nElection bye-laws and manifesto rules are accessible on the student portal.\n\nDirector, Student Affairs\nSRM University-AP`,
    timestamp: "2026-09-27T15:00:00.000Z",
    dateFormatted: "Sep 27, 2026 · 3:00 PM",
    category: "ADMINISTRATION",
    priority: "LOW",
    priorityScore: 38,
    priorityReason: "Informational nomination guidelines for upcoming student council elections.",
    categoryReason: "Student affairs governance circular.",
    summary: "Student Council nomination guidelines released. Nominations open Oct 12–15 for CGPA 7.5+.",
    actionRequired: false,
    location: "Directorate of Student Affairs",
    affectedGroup: "All SRM AP Students",
    urgency: "LOW",
    tags: ["elections", "student-council", "dsa", "governance"],
    isRead: true,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-council-elections"
  },

  // 30. SPORTS COMPLEX PORTAL (LOW)
  {
    id: "email-srm-030",
    sender: "sports@srmap.edu.in",
    senderName: "Department of Physical Education",
    recipient: "demo.student@srmap.edu.in",
    subject: "Indoor Sports Complex & Badminton Court Booking Portal Launch",
    body: `Dear Campus Residents,\n\nTo ensure fair court allocation, bookings for Indoor Badminton, Squash, and Table Tennis courts must now be reserved online via https://sports.srmap.edu.in.\n\n- Slot Times: 6:00 AM – 8:30 AM & 4:30 PM – 9:00 PM\n- Advance Booking: Up to 24 hours prior\n- Non-marking shoes mandatory\n\nPhysical Education Cell\nSRM University-AP`,
    timestamp: "2026-09-28T08:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 8:00 AM",
    category: "FACILITIES",
    priority: "LOW",
    priorityScore: 30,
    priorityReason: "Facility booking portal announcement for campus indoor sports courts.",
    categoryReason: "Campus recreational sports facility operational update.",
    summary: "New online court reservation system for badminton and squash courts launched.",
    actionRequired: false,
    location: "Indoor Sports Complex",
    affectedGroup: "Campus Sports Enthusiasts",
    urgency: "LOW",
    tags: ["sports", "badminton", "booking", "facilities"],
    isRead: true,
    source: "demo",
    systemOrigin: "Campus Location",
    threadId: "thread-sports-portal"
  },

  // 31. HEALTH CHECKUP CAMP (LOW)
  {
    id: "email-srm-031",
    sender: "health@srmap.edu.in",
    senderName: "Campus Health & Wellness Center",
    recipient: "demo.student@srmap.edu.in",
    subject: "Annual Student Health & Ophthalmic Screening Camp (Oct 6–8)",
    body: `Dear Students,\n\nThe Campus Health and Wellness Center, in collaboration with AIIMS Mangalagiri, is conducting a free health checkup camp:\n\n- Dates: October 6 – 8, 2026 (9:30 AM – 3:30 PM)\n- Services: Eye Checkups, Dental Screening, Complete Blood Count, BMI & Ergonomics\n- Venue: Ground Floor, Health Center (Adjacent to Hostel Block C)\n\nMedical Officer\nSRM University-AP`,
    timestamp: "2026-09-27T13:00:00.000Z",
    dateFormatted: "Sep 27, 2026 · 1:00 PM",
    category: "FACILITIES",
    priority: "LOW",
    priorityScore: 32,
    priorityReason: "Free voluntary annual student health screening in collaboration with AIIMS.",
    categoryReason: "Campus medical and wellness facility announcement.",
    summary: "Free annual student health & eye checkup camp from Oct 6–8 at Campus Health Center.",
    actionRequired: false,
    location: "Campus Health Center",
    affectedGroup: "All Students",
    urgency: "LOW",
    tags: ["health", "checkup", "aiims", "wellness", "medical"],
    isRead: true,
    source: "demo",
    systemOrigin: "Campus Location",
    threadId: "thread-health-camp"
  },

  // 32. REVISED MESS MENU (LOW)
  {
    id: "email-srm-032",
    sender: "mess@srmap.edu.in",
    senderName: "Hostel Mess & Dining Committee",
    recipient: "demo.student@srmap.edu.in",
    subject: "Circular: Revised Student Mess Menu for October 2026",
    body: `Dear Hostel Boarders,\n\nBased on feedback gathered at the Joint Student-Mess Committee meeting, the revised dining menu for October 2026 is published.\n\nKey additions include South Indian breakfast specials (Guntur Karam Dosa, Pesarattu), expanded salad counters, and seasonal fruit distribution.\n\nMess Committee\nSRM University-AP`,
    timestamp: "2026-09-28T12:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 12:00 PM",
    category: "HOSTEL",
    priority: "LOW",
    priorityScore: 28,
    priorityReason: "Routine monthly dining hall menu revision based on student survey.",
    categoryReason: "Hostel dining and catering notice.",
    summary: "October revised hostel mess menu published with regional breakfast and salad additions.",
    actionRequired: false,
    location: "Campus Dining Halls",
    affectedGroup: "Hostel Boarders",
    urgency: "LOW",
    tags: ["mess", "menu", "dining", "hostel", "food"],
    isRead: true,
    source: "demo",
    systemOrigin: "Campus Location",
    threadId: "thread-mess-menu"
  },

  // 33. GOOGLE CLASSROOM: CSE 207 LAB REPORT 3 (HIGH)
  {
    id: "email-srm-033",
    sender: "classroom-notice@srmap.edu.in",
    senderName: "Google Classroom — CSE 207 Digital Electronics",
    recipient: "demo.student@srmap.edu.in",
    subject: "Assignment Posted: 'Lab Report 3: Synchronous Decade Counter Implementation'",
    body: `[Google Classroom: CSE 207 - Digital Electronics]\n\nDr. Anand Kumar posted a new assignment:\n\n'Lab Report 3: Synchronous Decade Counter Implementation'\nDue Date: Friday, October 2, 2026 at 5:00 PM.\n\nUpload your Logisim simulation schematic files and observation truth tables with state transition diagrams.\n\nLate submissions will receive a 20% mark deduction per day.\n\nMaximum Points: 30`,
    timestamp: "2026-09-28T19:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 7:00 PM",
    category: "ASSIGNMENTS",
    priority: "HIGH",
    priorityScore: 80,
    priorityReason: "Graded lab simulation assignment due Friday at 5:00 PM with late penalty clause.",
    categoryReason: "Google Classroom laboratory assignment posting.",
    summary: "CSE 207 Lab Report 3 on Decade Counters due Oct 2, 5 PM on Google Classroom.",
    actionRequired: true,
    actionText: "Upload Logisim schematic files for CSE 207 Lab Report 3 before Friday 5 PM",
    actionDeadline: "Friday, Oct 2, 2026 · 5:00 PM",
    deadlineDate: "2026-10-02T11:30:00.000Z",
    location: "Google Classroom Portal",
    affectedGroup: "CSE Semester 3 Students",
    urgency: "HIGH",
    tags: ["google-classroom", "cse207", "digital-electronics", "logisim", "lab-report"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-cse207-classroom",
    relatedClassroomWorkId: "work-3"
  },

  // 34. GDG SOLUTION HUNT VENUE UPDATE (thread with 008) (MEDIUM)
  {
    id: "email-srm-034",
    sender: "communications@srmap.edu.in",
    senderName: "GDG on Campus — SRM University AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "GDG Solution Hunt Challenge: Team Seating & Wi-Fi Access Credentials",
    body: `Dear Registered Participants,\n\nPlease arrive at X-Lab Auditorium by 8:45 AM for team verification.\n\nWi-Fi Access SSID: GDG_SPRINT_2026\nPre-installed software: Flutter SDK 3.24 / Node.js 20+ / Android Studio.\n\nMentorship sessions start at 10:30 AM.\n\nGDG on Campus Organising Committee\nSRM University-AP`,
    timestamp: "2026-09-28T15:30:00.000Z",
    dateFormatted: "Sep 28, 2026 · 3:30 PM",
    category: "HACKATHONS",
    priority: "MEDIUM",
    priorityScore: 68,
    priorityReason: "Detailed logistical instructions and credentials for tomorrow's hackathon at X-Lab.",
    categoryReason: "Follow-up hackathon team briefing.",
    summary: "Report to X-Lab Auditorium by 8:45 AM for GDG Solution Hunt. Wi-Fi: GDG_SPRINT_2026.",
    actionRequired: true,
    actionText: "Arrive at X-Lab Auditorium by 8:45 AM for GDG Hackathon check-in",
    actionDeadline: "Today, 8:45 AM",
    deadlineDate: "2026-09-29T03:15:00.000Z",
    location: "X-Lab Auditorium",
    affectedGroup: "GDG Solution Hunt Teams",
    urgency: "MEDIUM",
    tags: ["gdg", "hackathon", "x-lab", "wi-fi", "briefing"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-gdg-hunt"
  },

  // 35. ROBOTICS WORKSHOP PREREQUISITES (thread with 002) (HIGH)
  {
    id: "email-srm-035",
    sender: "communications@srmap.edu.in",
    senderName: "Directorate of Communications",
    recipient: "demo.student@srmap.edu.in",
    subject: "Robotics Workshop: Hardware Kit Checklist & ROS Software Setup",
    body: `Dear Robotics Workshop Registrants,\n\nTo ensure zero delays during tomorrow's hands-on robotics session in S202 SR Block:\n\n1. Install ROS 2 (Humble Hawksbill) or download our pre-configured VirtualBox VM.\n2. Ensure USB-UART drivers for CH340 are enabled on your machine.\n3. Micro-ROS microcontrollers will be issued at 9:50 AM in S202.\n\nDr. Teja Krishna Mamidi\nDepartment of Mechanical Engineering, SRM AP`,
    timestamp: "2026-09-29T08:30:00.000Z",
    dateFormatted: "Sep 29, 2026 · 8:30 AM",
    category: "EVENTS",
    priority: "HIGH",
    priorityScore: 78,
    priorityReason: "Technical prerequisites checklist for tomorrow's robotics session in S202 SR Block.",
    categoryReason: "Workshop software preparation instructions.",
    summary: "Download ROS 2 VM and USB-UART drivers for tomorrow's robotics workshop in S202 SR Block.",
    actionRequired: true,
    actionText: "Install ROS 2 VirtualBox image before attending S202 robotics lab tomorrow",
    actionDeadline: "Sep 30, 2026 · 9:30 AM",
    deadlineDate: "2026-09-30T04:00:00.000Z",
    location: "S202, SR Block",
    affectedGroup: "Registered Workshop Students",
    urgency: "HIGH",
    tags: ["robotics", "ros2", "s202", "prerequisites", "techfest"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-robotics-workshop"
  },

  // 36. HATCHLAB SEED FUNDING (MEDIUM)
  {
    id: "email-srm-036",
    sender: "ecell@srmap.edu.in",
    senderName: "HatchLab Incubation Center, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "Call for Proposals: HatchLab Innovation Seed Grants (Up to ₹2,50,000)",
    body: `Dear Student Innovators,\n\nHatchLab Incubation Center invites early-stage deep-tech, AI, and hardware venture applications for Seed Grant Cohort 4.\n\n- Grant Amount: Up to ₹2.5 Lakhs per student team\n- Facility: Prototyping lab, patent filing support, cloud credits\n- Application Deadline: October 15, 2026\n\nApply with a 10-slide deck on https://hatchlab.srmap.edu.in.\n\nDirectorate of Entrepreneurship & Innovation\nSRM University-AP`,
    timestamp: "2026-09-26T14:30:00.000Z",
    dateFormatted: "Sep 26, 2026 · 2:30 PM",
    category: "ENTREPRENEURSHIP",
    priority: "MEDIUM",
    priorityScore: 68,
    priorityReason: "Student startup seed funding grant opportunity up to ₹2.5 Lakhs with Oct 15 deadline.",
    categoryReason: "University incubator seed grant call.",
    summary: "HatchLab Cohort 4 seed grants up to ₹2.5 Lakhs open for student startups until Oct 15.",
    actionRequired: true,
    actionText: "Submit executive proposal deck on HatchLab portal before Oct 15",
    actionDeadline: "Oct 15, 2026 · 11:59 PM",
    deadlineDate: "2026-10-15T18:29:00.000Z",
    location: "HatchLab Incubation Center",
    affectedGroup: "Student Entrepreneurs",
    urgency: "MEDIUM",
    tags: ["ecell", "hatchlab", "seed-funding", "grants", "startups"],
    isRead: false,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-hatchlab-grant"
  },

  // 37. SEAS RESEARCH INTERNSHIPS (MEDIUM)
  {
    id: "email-srm-037",
    sender: "dean.seas@srmap.edu.in",
    senderName: "Office of the Dean, SEAS",
    recipient: "demo.student@srmap.edu.in",
    subject: "Undergraduate Research Opportunities Programme (UROP) — Fall 2026",
    body: `Dear Engineering Students,\n\nSEAS announces 25 faculty-mentored research fellowships under UROP:\n\n- Domains: Edge AI, 6G Wireless, Neuromorphic Chips, Quantum Computing\n- Stipend: ₹6,000 per month for 6 months\n- Eligibility: B.Tech 2nd & 3rd year with CGPA 8.2+\n- Selection: Technical interview based on research proposal\n\nApply by October 10 at dean.seas@srmap.edu.in with statement of purpose.\n\nDean, School of Engineering and Sciences\nSRM University-AP`,
    timestamp: "2026-09-27T17:00:00.000Z",
    dateFormatted: "Sep 27, 2026 · 5:00 PM",
    category: "ACADEMICS",
    priority: "MEDIUM",
    priorityScore: 72,
    priorityReason: "Paid undergraduate research fellowship with ₹6,000 monthly stipend.",
    categoryReason: "Faculty research mentorship programme.",
    summary: "SEAS UROP research fellowships (₹6,000/mo) in Edge AI and Quantum Computing. Apply by Oct 10.",
    actionRequired: true,
    actionText: "Email statement of purpose to dean.seas@srmap.edu.in for UROP before Oct 10",
    actionDeadline: "Oct 10, 2026 · 5:00 PM",
    deadlineDate: "2026-10-10T11:30:00.000Z",
    location: "SEAS Research Labs",
    affectedGroup: "B.Tech Students with CGPA 8.2+",
    urgency: "MEDIUM",
    tags: ["urop", "research", "seas", "stipend", "edge-ai"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-urop-research"
  },

  // 38. WI-FI UPGRADE IN SR BLOCK (LOW)
  {
    id: "email-srm-038",
    sender: "it.support@srmap.edu.in",
    senderName: "IT Services Directorate",
    recipient: "demo.student@srmap.edu.in",
    subject: "Campus IT Notice: Wi-Fi 6 Access Point Upgrades in SR Block Tonight",
    body: `Dear Students and Faculty,\n\nIT Services is upgrading the campus backbone to Wi-Fi 6 across SR Block floors 1, 2, and 3:\n\n- Maintenance Window: Tonight, 11:30 PM to 2:30 AM\n- Expected Impact: 15-minute intermittent disconnection on 'SRMAP-Student' SSID\n- Wired Ethernet in labs will remain operational\n\nIT Services Directorate\nSRM University-AP`,
    timestamp: "2026-09-28T16:45:00.000Z",
    dateFormatted: "Sep 28, 2026 · 4:45 PM",
    category: "FACILITIES",
    priority: "LOW",
    priorityScore: 26,
    priorityReason: "Scheduled nocturnal network maintenance with brief Wi-Fi downtime in SR Block.",
    categoryReason: "Campus IT infrastructure upgrade advisory.",
    summary: "Wi-Fi 6 upgrade in SR Block tonight from 11:30 PM to 2:30 AM with brief interruptions.",
    actionRequired: false,
    location: "SR Block Floors 1–3",
    affectedGroup: "SR Block Users",
    urgency: "LOW",
    tags: ["it-support", "wifi", "maintenance", "sr-block"],
    isRead: true,
    source: "demo",
    systemOrigin: "Campus Location",
    threadId: "thread-wifi-upgrade"
  },

  // 39. NSS BLOOD DONATION CAMP (LOW)
  {
    id: "email-srm-039",
    sender: "nss@srmap.edu.in",
    senderName: "NSS & Youth Red Cross Cell",
    recipient: "demo.student@srmap.edu.in",
    subject: "Voluntary Blood Donation Camp on Gandhi Jayanti (Oct 2)",
    body: `Dear Students and Volunteers,\n\nThe National Service Scheme (NSS) unit of SRM University-AP, in association with the Government General Hospital Guntur, is organizing a Mega Voluntary Blood Donation Drive:\n\n- Date: Friday, October 2, 2026 (Gandhi Jayanti)\n- Time: 9:30 AM – 3:30 PM\n- Venue: Student Activity Center (SAC), Ground Floor\n\nDonors receive certificate of appreciation and refreshment kit.\n\nNSS Coordinator\nSRM University-AP`,
    timestamp: "2026-09-27T10:15:00.000Z",
    dateFormatted: "Sep 27, 2026 · 10:15 AM",
    category: "CLUBS",
    priority: "LOW",
    priorityScore: 32,
    priorityReason: "Voluntary community social service drive on Gandhi Jayanti at SAC.",
    categoryReason: "National Service Scheme social welfare drive.",
    summary: "NSS Voluntary Blood Donation Camp on Oct 2 at SAC Ground Floor from 9:30 AM to 3:30 PM.",
    actionRequired: false,
    location: "Student Activity Center (SAC)",
    affectedGroup: "All SRM AP Community",
    urgency: "LOW",
    tags: ["nss", "blood-donation", "gandhi-jayanti", "community-service"],
    isRead: true,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-nss-donation"
  },

  // 40. GOOGLE CLASSROOM: SEC 203 APTITUDE TEST (MEDIUM)
  {
    id: "email-srm-040",
    sender: "classroom-notice@srmap.edu.in",
    senderName: "Google Classroom — SEC 203 Aptitude for Engineers",
    recipient: "demo.student@srmap.edu.in",
    subject: "Assignment Posted: 'Practice Test 1: Quantitative Aptitude & Data Interpretation'",
    body: `[Google Classroom: SEC 203 - Aptitude for Engineers III]\n\nPlacement Training Cell posted:\n\n'Practice Test 1: Quantitative Aptitude & Data Interpretation'\nDue Date: Tuesday, October 6, 2026 at 11:59 PM.\n\nModules: Time & Distance, Probability, Permutations, Syllogisms, and Table Chart Interpretation. 40 MCQs with 60-minute countdown.\n\nMandatory diagnostic assessment for semester placement eligibility.\n\nMaximum Points: 40`,
    timestamp: "2026-09-28T20:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 8:00 PM",
    category: "ASSIGNMENTS",
    priority: "MEDIUM",
    priorityScore: 74,
    priorityReason: "Diagnostic placement aptitude test with mandatory completion clause by Oct 6.",
    categoryReason: "Google Classroom placement training assessment.",
    summary: "SEC 203 Aptitude Practice Test 1 posted. 40 MCQs due on Google Classroom by Oct 6, 11:59 PM.",
    actionRequired: true,
    actionText: "Take SEC 203 60-minute Aptitude Practice Test on Google Classroom",
    actionDeadline: "Oct 6, 2026 · 11:59 PM",
    deadlineDate: "2026-10-06T18:29:00.000Z",
    location: "Google Classroom Portal",
    affectedGroup: "All B.Tech 3rd Semester Students",
    urgency: "MEDIUM",
    tags: ["google-classroom", "sec203", "aptitude", "placement-prep", "quant"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-sec203-aptitude",
    relatedClassroomWorkId: "work-4"
  },

  // 41. VIJAYAWADA EXPRESS SHUTTLE REVISED TIMINGS (LOW)
  {
    id: "email-srm-041",
    sender: "transport@srmap.edu.in",
    senderName: "Transport Operations Cell",
    recipient: "demo.student@srmap.edu.in",
    subject: "Evening Campus Shuttle Route 12: Vijayawada Express Timings",
    body: `Dear Day Scholars,\n\nEffective Wednesday, September 30, Evening Shuttle Route 12 (Campus to Vijayawada Railway Station via Ramavarappadu Ring) will operate two departure waves:\n\n- Wave 1: 5:15 PM (Early departure for lab students)\n- Wave 2: 6:45 PM (Standard departure for library students)\n\nBoth shuttles depart from Bay 4.\n\nTransport Cell, SRM University-AP`,
    timestamp: "2026-09-28T14:15:00.000Z",
    dateFormatted: "Sep 28, 2026 · 2:15 PM",
    category: "TRANSPORT",
    priority: "LOW",
    priorityScore: 36,
    priorityReason: "New evening bus schedule wave additions for Vijayawada commuters.",
    categoryReason: "Campus shuttle timetable update.",
    summary: "Route 12 evening shuttle now leaves at 5:15 PM and 6:45 PM from Bay 4 to Vijayawada.",
    actionRequired: false,
    location: "Main Gate Bay 4",
    affectedGroup: "Vijayawada Day Scholars",
    urgency: "LOW",
    tags: ["transport", "shuttle", "vijayawada", "timetable"],
    isRead: true,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-transport-transit"
  },

  // 42. ALUMNI MENTORSHIP FALL 2026 (LOW)
  {
    id: "email-srm-042",
    sender: "alumni@srmap.edu.in",
    senderName: "Directorate of Alumni Relations",
    recipient: "demo.student@srmap.edu.in",
    subject: "Alumni-Student Mentorship Programme: 1-on-1 Matching Open",
    body: `Dear Sophomore Students,\n\nConnect with alumni working at Google, Amazon, Qualcomm, and NVIDIA through our 1-on-1 Alumni Mentorship Programme.\n\n- Duration: 8 weeks (Bi-weekly 45-min Zoom sessions)\n- Focus: Career roadmap, coding interviews, higher studies abroad (MS/PhD)\n- Registration: Open on the Alumni Portal until October 10\n\nDirectorate of Alumni Relations\nSRM University-AP`,
    timestamp: "2026-09-27T12:00:00.000Z",
    dateFormatted: "Sep 27, 2026 · 12:00 PM",
    category: "GENERAL",
    priority: "LOW",
    priorityScore: 40,
    priorityReason: "Voluntary career mentorship registration open with alumni working in top tech firms.",
    categoryReason: "Alumni relations career mentoring opportunity.",
    summary: "1-on-1 Alumni Mentorship matching open until Oct 10 with engineers at Google, Qualcomm, and Amazon.",
    actionRequired: false,
    location: "Online (Zoom)",
    affectedGroup: "All 2nd and 3rd Year Students",
    urgency: "LOW",
    tags: ["alumni", "mentorship", "career", "networking"],
    isRead: true,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-alumni-mentor"
  },

  // 43. LANGUAGE LAB ASSESSMENT (MEDIUM)
  {
    id: "email-srm-043",
    sender: "easwari.arts@srmap.edu.in",
    senderName: "Easwari School of Liberal Arts",
    recipient: "demo.student@srmap.edu.in",
    subject: "Language Lab Diagnostic: Oral Presentation & Phonetics Check (Oct 7)",
    body: `Dear Engineering Students,\n\nDiagnostic speaking assessments for Communicative English will be held in the Digital Language Lab (Room S204, SR Block) on Wednesday, October 7, from 2:00 PM to 4:00 PM.\n\nEvaluation rubric covers technical pitch delivery, pronunciation clarity, and Q&A interaction.\n\nDepartment of English\nEaswari School of Liberal Arts, SRM University-AP`,
    timestamp: "2026-09-28T09:45:00.000Z",
    dateFormatted: "Sep 28, 2026 · 9:45 AM",
    category: "ACADEMICS",
    priority: "MEDIUM",
    priorityScore: 58,
    priorityReason: "Scheduled oral presentation assessment in Room S204 SR Block.",
    categoryReason: "Liberal arts language curriculum assessment.",
    summary: "Oral communicative English assessment in Room S204 SR Block on Wednesday, Oct 7, 2–4 PM.",
    actionRequired: true,
    actionText: "Prepare 2-minute technical pitch for Language Lab assessment on Oct 7",
    actionDeadline: "Oct 7, 2026 · 2:00 PM",
    deadlineDate: "2026-10-07T08:30:00.000Z",
    location: "Room S204, SR Block",
    affectedGroup: "B.Tech Students in Communicative English",
    urgency: "MEDIUM",
    tags: ["liberal-arts", "english", "language-lab", "presentation", "sr-block"],
    isRead: false,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-language-lab"
  },

  // 44. PAARI SCHOOL OF BUSINESS FINTECH SUMMIT (MEDIUM)
  {
    id: "email-srm-044",
    sender: "paari.business@srmap.edu.in",
    senderName: "Paari School of Business, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "National FinTech Summit 2026 — Call for Student Delegates & Posters",
    body: `Dear Scholars,\n\nPaari School of Business announces the National FinTech Summit 2026 on 'Decentralized Finance, UPI Global Integrations, and Algorithmic Trading':\n\n- Date: October 23 – 24, 2026\n- Keynote: Leaders from NPCI and Reserve Bank Innovation Hub\n- Poster Presentation Prize: ₹25,000\n- Abstract Submission Deadline: October 8, 2026\n\nPaari School of Business\nSRM University-AP, Andhra Pradesh`,
    timestamp: "2026-09-27T18:00:00.000Z",
    dateFormatted: "Sep 27, 2026 · 6:00 PM",
    category: "EVENTS",
    priority: "MEDIUM",
    priorityScore: 55,
    priorityReason: "FinTech conference call for posters with ₹25,000 prize; abstract deadline Oct 8.",
    categoryReason: "Business school national symposium call for papers.",
    summary: "National FinTech Summit call for posters open until Oct 8. Event on Oct 23–24.",
    actionRequired: false,
    location: "Main Auditorium",
    affectedGroup: "All University Students",
    urgency: "MEDIUM",
    tags: ["paari-business", "fintech", "summit", "conference", "npci"],
    isRead: true,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-fintech-summit"
  },

  // 45. CIVIL ENGG MODEL EXPO (LOW)
  {
    id: "email-srm-045",
    sender: "civil.dept@srmap.edu.in",
    senderName: "Department of Civil Engineering, SEAS",
    recipient: "demo.student@srmap.edu.in",
    subject: "Smart Infrastructure Expo 2026: Working Models Exhibition in SR Foyer",
    body: `Dear Campus Community,\n\nThe Department of Civil Engineering invites all students to inspect working structural prototypes at the Smart Infrastructure Expo:\n\n- Projects: Earthquake-Resistant Dampers, Self-Healing Bio-Concrete, Smart Drainage Systems for Amaravati\n- Venue: Ground Floor Foyer, SR Block\n- Timing: October 5, 2026 · 10:00 AM – 4:00 PM\n\nDepartment of Civil Engineering, SEAS\nSRM University-AP`,
    timestamp: "2026-09-28T10:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 10:00 AM",
    category: "TECH EVENTS",
    priority: "LOW",
    priorityScore: 34,
    priorityReason: "Departmental project exhibition in SR Block foyer.",
    categoryReason: "Civil engineering student showcase.",
    summary: "Civil Engineering Smart Infrastructure Expo on Oct 5 in SR Block Foyer (10 AM - 4 PM).",
    actionRequired: false,
    location: "Ground Floor Foyer, SR Block",
    affectedGroup: "All Students",
    urgency: "LOW",
    tags: ["civil", "smart-infra", "expo", "sr-block", "prototypes"],
    isRead: true,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-civil-expo"
  },

  // 46. BIOLOGICAL SCIENCES CRISPR LECTURE (LOW)
  {
    id: "email-srm-046",
    sender: "bio.dept@srmap.edu.in",
    senderName: "Department of Biological Sciences, SEAS",
    recipient: "demo.student@srmap.edu.in",
    subject: "Distinguished Seminar: 'Translational CRISPR Applications in Molecular Oncology'",
    body: `Dear Scholars,\n\nThe Department of Biological Sciences is hosting Dr. K. Venkataraman, Senior Scientist at CCMB Hyderabad:\n\n- Topic: 'Translational CRISPR Applications in Molecular Oncology'\n- Date: Friday, October 9, 2026\n- Time: 3:00 PM – 4:30 PM\n- Venue: Seminar Hall 1, Admin Block\n\nOpen to all students interested in bioinformatics and biotechnology.\n\nDepartment of Biological Sciences\nSchool of Engineering and Sciences, SRM University-AP`,
    timestamp: "2026-09-27T16:30:00.000Z",
    dateFormatted: "Sep 27, 2026 · 4:30 PM",
    category: "ACADEMICS",
    priority: "LOW",
    priorityScore: 36,
    priorityReason: "Specialist guest seminar in molecular oncology and bioinformatics.",
    categoryReason: "Biological sciences seminar announcement.",
    summary: "Distinguished CRISPR Seminar by CCMB Scientist on Oct 9, 3 PM in Seminar Hall 1 Admin Block.",
    actionRequired: false,
    location: "Seminar Hall 1, Admin Block",
    affectedGroup: "Bio & Engineering Students",
    urgency: "LOW",
    tags: ["biology", "crispr", "oncology", "ccmb", "seminar"],
    isRead: true,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-bio-seminar"
  },

  // 47. ANTI-RAGGING CIRCULAR (LOW)
  {
    id: "email-srm-047",
    sender: "registrar.office@srmap.edu.in",
    senderName: "Registrar Office, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "Statutory Circular: Zero Tolerance Policy towards Ragging (UGC Bylaws)",
    body: `Dear Students,\n\nSRM University-AP maintains an absolute zero-tolerance policy against any form of ragging or harassment on campus premises, hostels, and university transit.\n\nAny student found violating statutory UGC regulations faces immediate suspension, academic expulsion, and police intimation under IPC sections.\n\n24/7 Anti-Ragging Helpline: 1800-180-5522\nCampus Proctorial Board Desk: Ext 205\n\nRegistrar Office\nSRM University-AP, Andhra Pradesh`,
    timestamp: "2026-09-26T09:00:00.000Z",
    dateFormatted: "Sep 26, 2026 · 9:00 AM",
    category: "ADMINISTRATION",
    priority: "LOW",
    priorityScore: 30,
    priorityReason: "Statutory UGC anti-ragging compliance circular and emergency proctorial numbers.",
    categoryReason: "University statutory compliance notification.",
    summary: "Zero-tolerance anti-ragging circular. 24/7 helpline 1800-180-5522 and campus proctor desk Ext 205.",
    actionRequired: false,
    location: "University Wide",
    affectedGroup: "All Students",
    urgency: "LOW",
    tags: ["anti-ragging", "ugc", "statutory", "registrar", "safety"],
    isRead: true,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-anti-ragging"
  },

  // 48. IEEE PAPER PRESENTATION (LOW)
  {
    id: "email-srm-048",
    sender: "ieee@srmap.edu.in",
    senderName: "IEEE Student Branch, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "IEEE TechPulse 2026: Annual Technical Paper Presentation Contest",
    body: `Greetings IEEE Members,\n\nSubmit your original research manuscripts for IEEE TechPulse 2026:\n\n- Tracks: Signal Processing, IoT Systems, Deep Learning, Power Electronics\n- Full Paper Deadline: October 14, 2026\n- Accepted papers will receive IEEE Student Branch Certificates and travel grants for international conference registration.\n\nIEEE Student Branch, SRM AP`,
    timestamp: "2026-09-28T15:00:00.000Z",
    dateFormatted: "Sep 28, 2026 · 3:00 PM",
    category: "CLUBS",
    priority: "LOW",
    priorityScore: 38,
    priorityReason: "Call for conference papers from IEEE student branch.",
    categoryReason: "Student technical society conference paper contest.",
    summary: "IEEE TechPulse 2026 call for research papers open until Oct 14 with travel grants for winners.",
    actionRequired: false,
    location: "Online Submission Portal",
    affectedGroup: "Engineering Students",
    urgency: "LOW",
    tags: ["ieee", "paper-contest", "research", "signal-processing"],
    isRead: true,
    source: "demo",
    systemOrigin: "Student Activity",
    threadId: "thread-ieee-paper"
  },

  // 49. RAMANUJAN MATHS OLYMPIAD (LOW)
  {
    id: "email-srm-049",
    sender: "math.dept@srmap.edu.in",
    senderName: "Department of Mathematics, SEAS",
    recipient: "demo.student@srmap.edu.in",
    subject: "Ramanujan Mathematics Olympiad: Intra-University Prelims on Oct 10",
    body: `Dear Students,\n\nThe Department of Mathematics invites registrations for the Ramanujan Mathematics Olympiad preliminary qualifier:\n\n- Date: Saturday, October 10, 2026 (Compensatory Day)\n- Time: 4:30 PM – 6:00 PM\n- Venue: Room S102, SR Block\n- Syllabus: Discrete Mathematics, Linear Algebra, Real Analysis, Combinatorics\n\nTop 10 qualifiers represent SRM University-AP at the National Inter-University Mathematics Olympiad.\n\nDepartment of Mathematics, SEAS`,
    timestamp: "2026-09-27T11:00:00.000Z",
    dateFormatted: "Sep 27, 2026 · 11:00 AM",
    category: "ACADEMICS",
    priority: "LOW",
    priorityScore: 38,
    priorityReason: "Voluntary mathematical olympiad qualifier taking place on October 10 compensatory working day.",
    categoryReason: "Mathematics department competition.",
    summary: "Ramanujan Mathematics Olympiad intra-university prelims on Oct 10, 4:30 PM in S102 SR Block.",
    actionRequired: false,
    location: "Room S102, SR Block",
    affectedGroup: "All Students",
    urgency: "LOW",
    tags: ["mathematics", "olympiad", "ramanujan", "discrete-math"],
    isRead: true,
    source: "demo",
    systemOrigin: "Academic Portal",
    threadId: "thread-math-olympiad"
  },

  // 50. UNIVERSITY MONTHLY DIGEST (LOW)
  {
    id: "email-srm-050",
    sender: "communications@srmap.edu.in",
    senderName: "Directorate of Communications, SRM University-AP",
    recipient: "demo.student@srmap.edu.in",
    subject: "SRM AP Monthly Digest: September 2026 Campus Highlights",
    body: `Dear Members of SRM University-AP,\n\nCatch up on notable institutional achievements from September 2026 in our monthly newsletter:\n\n- ₹4.2 Crore DST Research Grant awarded to SEAS Nanotechnology Lab\n- MoUs signed with leading Taiwanese semiconductor fabrication institutes\n- Highlights from the Techfest IIT Bombay Robotics Workshop and Terrathon 2026\n- Student startup incubated at HatchLab receives national angel funding\n\nRead the full interactive magazine on the university portal.\n\nDirectorate of Communications\nSRM University-AP, Andhra Pradesh\nNeerukonda, Mangalagiri Mandal, Guntur - 522240`,
    timestamp: "2026-09-29T07:00:00.000Z",
    dateFormatted: "Sep 29, 2026 · 7:00 AM",
    category: "GENERAL",
    priority: "LOW",
    priorityScore: 24,
    priorityReason: "Monthly general institutional newsletter and campus achievement digest.",
    categoryReason: "Informational monthly digest.",
    summary: "SRM AP September Digest: DST grants, semiconductor MoUs, HatchLab startup achievements.",
    actionRequired: false,
    location: "SRM AP Web Portal",
    affectedGroup: "All Campus Community",
    urgency: "LOW",
    tags: ["newsletter", "digest", "dst-grant", "communications", "achievements"],
    isRead: true,
    source: "demo",
    systemOrigin: "Administrative Portal",
    threadId: "thread-monthly-digest"
  }
];

// Write dataset to all 3 standard locations
export function generateDataset() {
  console.log(`Writing exactly ${exact50DemoEmails.length} demo emails...`);
  if (exact50DemoEmails.length !== 50) {
    throw new Error(`Expected exactly 50 emails, but got ${exact50DemoEmails.length}`);
  }

  const jsonContent = JSON.stringify(exact50DemoEmails, null, 2);

  const paths = [
    path.resolve(__dirname, '../../../data/demo-emails/university-emails.json'),
    path.resolve(__dirname, '../data/demo-emails.json'),
    path.resolve(__dirname, '../../../client/src/data/demo-emails.json')
  ];

  paths.forEach(p => {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, jsonContent, 'utf-8');
    console.log(`✓ Wrote exactly 50 emails to: ${p}`);
  });
}

if (require.main === module) {
  generateDataset();
}
